/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cafe_Management_Systems;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Scanner;
/**
 *
 * @author Pentazoid
 */
public class Cafe_Management_System extends javax.swing.JFrame {
 double[] drink=new double[5];
 double[] cakes=new double[5];
 double[] costs=new double[3];
 double[] i=new double[12];
 
 
    /**
     * Creates new form Cafe_Management_System
     */
    public Cafe_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receiptTextArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        receiptButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        totalButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        icedLatteCheckBox = new javax.swing.JCheckBox();
        espressoCheckBox = new javax.swing.JCheckBox();
        cappuccinoCheckBox = new javax.swing.JCheckBox();
        icedCappuccinoCheckBox = new javax.swing.JCheckBox();
        latteCheckBox = new javax.swing.JCheckBox();
        icedLatteTextField = new javax.swing.JTextField();
        latteTextField = new javax.swing.JTextField();
        espressoTextField = new javax.swing.JTextField();
        cappuccinoTextField = new javax.swing.JTextField();
        icedCappuccinoTextField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        carrotCakeCheckBox = new javax.swing.JCheckBox();
        shortCakeCheckBox = new javax.swing.JCheckBox();
        cheeseCakeCheckBox = new javax.swing.JCheckBox();
        peachCakeCheckBox = new javax.swing.JCheckBox();
        coffeeCakeCheckBox = new javax.swing.JCheckBox();
        coffeeCakeTextField = new javax.swing.JTextField();
        carrotCakeTextField = new javax.swing.JTextField();
        shortCakeTextField = new javax.swing.JTextField();
        cheeseCakeTextField = new javax.swing.JTextField();
        peachCakeTextField = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        taxTextField = new javax.swing.JTextField();
        subTotalTextField = new javax.swing.JTextField();
        totalTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel9 = new javax.swing.JLabel();
        costOfDrinksTextField = new javax.swing.JTextField();
        costOfCakesTextField = new javax.swing.JTextField();
        serviceChargeTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1368, 730));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Cafe Management Systems");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(356, 356, 356))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        receiptTextArea.setColumns(20);
        receiptTextArea.setRows(5);
        jScrollPane1.setViewportView(receiptTextArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        receiptButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        receiptButton.setText("Receipt");
        receiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setText("exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        totalButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalButton.setText("Total");
        totalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(totalButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receiptButton)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalButton)
                    .addComponent(receiptButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(exitButton))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        icedLatteCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        icedLatteCheckBox.setText("Iced Latte");
        icedLatteCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icedLatteCheckBoxActionPerformed(evt);
            }
        });

        espressoCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        espressoCheckBox.setText("Espresso");
        espressoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espressoCheckBoxActionPerformed(evt);
            }
        });

        cappuccinoCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cappuccinoCheckBox.setText("Cappuccino");
        cappuccinoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuccinoCheckBoxActionPerformed(evt);
            }
        });

        icedCappuccinoCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        icedCappuccinoCheckBox.setText("Iced Cappuccino");
        icedCappuccinoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icedCappuccinoCheckBoxActionPerformed(evt);
            }
        });

        latteCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        latteCheckBox.setText("Latte");
        latteCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latteCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icedLatteCheckBox)
                            .addComponent(cappuccinoCheckBox)
                            .addComponent(espressoCheckBox)
                            .addComponent(latteCheckBox)))
                    .addComponent(icedCappuccinoCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icedCappuccinoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icedLatteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espressoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(latteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cappuccinoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(latteCheckBox)
                    .addComponent(latteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icedLatteCheckBox)
                    .addComponent(icedLatteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espressoCheckBox)
                    .addComponent(espressoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cappuccinoCheckBox)
                    .addComponent(cappuccinoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(icedCappuccinoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(icedCappuccinoCheckBox)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        carrotCakeCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        carrotCakeCheckBox.setText("Carrot Cake");
        carrotCakeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrotCakeCheckBoxActionPerformed(evt);
            }
        });

        shortCakeCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        shortCakeCheckBox.setText("Short Cake");
        shortCakeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortCakeCheckBoxActionPerformed(evt);
            }
        });

        cheeseCakeCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cheeseCakeCheckBox.setText("CheeseCake");
        cheeseCakeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseCakeCheckBoxActionPerformed(evt);
            }
        });

        peachCakeCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        peachCakeCheckBox.setText("Peach Cake");
        peachCakeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peachCakeCheckBoxActionPerformed(evt);
            }
        });

        coffeeCakeCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        coffeeCakeCheckBox.setText("Coffee Cake");
        coffeeCakeCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coffeeCakeCheckBoxMouseClicked(evt);
            }
        });
        coffeeCakeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeCakeCheckBoxActionPerformed(evt);
            }
        });

        cheeseCakeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseCakeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(peachCakeCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(peachCakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(cheeseCakeCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cheeseCakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(shortCakeCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shortCakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(carrotCakeCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(carrotCakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(coffeeCakeCheckBox)
                        .addGap(138, 138, 138)
                        .addComponent(coffeeCakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coffeeCakeCheckBox)
                    .addComponent(coffeeCakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carrotCakeCheckBox)
                    .addComponent(carrotCakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shortCakeCheckBox)
                    .addComponent(shortCakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheeseCakeCheckBox)
                    .addComponent(cheeseCakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peachCakeCheckBox)
                    .addComponent(peachCakeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tax");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Total");

        totalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Subtotal");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(taxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(226, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(taxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(103, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cost of Drinks");
        jLabel4.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Service Charge");

        costOfDrinksTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costOfDrinksTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Cost of Cakes");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(costOfDrinksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costOfCakesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serviceChargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addContainerGap(154, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(costOfDrinksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costOfCakesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(38, 38, 38)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceChargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                    .addContainerGap(142, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(142, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(325, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>                        

    private void icedCappuccinoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                       
       double cIcedCappuccino=Double.parseDouble(costOfDrinksTextField.getText());
       double IcedCappuccino=Double.parseDouble(icedCappuccinoTextField.getText());
       double iIcedCappucino=4.00;
       
       if(icedCappuccinoCheckBox.isSelected())
       {
           i[4]=(IcedCappuccino*iIcedCappucino)+cIcedCappuccino;
           String pDrink=String.format("%.2f",i[4]);
           costOfDrinksTextField.setText(pDrink);
           icedCappuccinoTextField.setText(pDrink);
       }

    }                                                      

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
     icedCappuccinoCheckBox.setSelected(false);
     cappuccinoCheckBox.setSelected(false);
     espressoCheckBox.setSelected(false);
     icedLatteCheckBox.setSelected(false);
     latteCheckBox.setSelected(false);
     icedCappuccinoTextField.setText("0");
     cappuccinoTextField.setText("0");
     espressoTextField.setText("0");
     icedLatteTextField.setText("0");
     latteTextField.setText("0");
     peachCakeCheckBox.setSelected(false);
     cheeseCakeCheckBox.setSelected(false);
     shortCakeCheckBox.setSelected(false);
     carrotCakeCheckBox.setSelected(false);
     coffeeCakeCheckBox.setSelected(false);
     peachCakeTextField.setText("0");
     coffeeCakeTextField.setText("0");
     carrotCakeTextField.setText("0");
     shortCakeTextField.setText("0");
     cheeseCakeTextField.setText("0");
     costOfDrinksTextField.setText("0");
     costOfCakesTextField.setText("0");
     serviceChargeTextField.setText("0");
     taxTextField.setText("0");
     subTotalTextField.setText("0");
     totalTextField.setText("0");
    }                                           

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        System.exit(0);
    }                                          

    private void receiptButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
      drink[4]=Double.parseDouble(icedCappuccinoTextField.getText());
      drink[3]=Double.parseDouble(cappuccinoTextField.getText());
      drink[2]=Double.parseDouble(espressoTextField.getText());
      drink[1]=Double.parseDouble(icedLatteTextField.getText());
      drink[0]=Double.parseDouble(latteTextField.getText());
      
      cakes[0]=Double.parseDouble(coffeeCakeTextField.getText());
      cakes[1]=Double.parseDouble(carrotCakeTextField.getText());
      cakes[2]=Double.parseDouble(shortCakeTextField.getText());
      cakes[3]=Double.parseDouble(cheeseCakeTextField.getText());
      cakes[4]=Double.parseDouble(peachCakeTextField.getText());
      costs[0]=Double.parseDouble(taxTextField.getText());
      costs[1]=Double.parseDouble(subTotalTextField.getText());
      costs[2]=Double.parseDouble(totalTextField.getText());
      //========================================================
      int refs;
      refs=1325+(int)(Math.random()+4328);
     // int ref=(refs);
      
      //========================================================
      Calendar timer=Calendar.getInstance();
      timer.getTime();
      SimpleDateFormat tTime=new SimpleDateFormat("MM:HH:SS");
      tTime.format(timer.getTime());
      SimpleDateFormat Tdate=new SimpleDateFormat("dd:MM:yyyy");
      Tdate.format(timer.getTime());
              
      receiptTextArea.append(" \t\n Cafe Management System: \n\n"+
              "Reference:\t\t\t"+refs+
              "Latte:\t\t"+drink[0]+
              "\nIced Latte:\t\t"+drink[1]+
              "\nEspresso:\t\t"+drink[2]+
              "\nCappuccino:\t\t"+drink[3]+
              "\nIced Cappuccino:\t\t"+drink[4]+
              "\n===========================\t\t"+
              "\nCoffee Cake:\t\t\t\t "+cakes[0]+
              "\nCarrot Cake:\t\t "+cakes[1]+
              "\nShort Cake:\t\t "+cakes[2]+
              "\nCheese Cake:\t\t "+cakes[3]+
              "\nPeach Cake:\t\t "+cakes[4] +
               "\n===========================\t\t"+
                "\nTax:\t "+costs[0]+
                 "\nSubtotal:\t "+costs[1]+
                  "\nTotal:\t "+costs[2]+
                 "\n===========================\t\t"+       
              "\nDate : "+Tdate.format(timer.getTime())+
              "\nTime :"+tTime.format(timer.getTime())+
              "\n\n\t\tThank you");
      
      
      
      
      
      
    }                                             

    private void cheeseCakeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void totalButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        drink[4]=Double.parseDouble(icedCappuccinoTextField.getText());
      drink[3]=Double.parseDouble(cappuccinoTextField.getText());
      drink[2]=Double.parseDouble(espressoTextField.getText());
      drink[1]=Double.parseDouble(icedLatteTextField.getText());
      drink[0]=Double.parseDouble(latteTextField.getText());
      
      cakes[0]=Double.parseDouble(coffeeCakeTextField.getText());
      cakes[1]=Double.parseDouble(carrotCakeTextField.getText());
      cakes[2]=Double.parseDouble(shortCakeTextField.getText());
      cakes[3]=Double.parseDouble(cheeseCakeTextField.getText());
      cakes[4]=Double.parseDouble(peachCakeTextField.getText());
      costs[0]=Double.parseDouble(taxTextField.getText());
      costs[1]=Double.parseDouble(subTotalTextField.getText());
      costs[2]=Double.parseDouble(totalTextField.getText());
      
      double cTotal=(drink[0]+drink[1]+drink[2]+drink[3]+drink[4]+cakes[0]+cakes[1]+cakes[2]+cakes[3]+cakes[4]);
      double allTotal=(cTotal);
      String iTotal=String.format("$ %.2f",allTotal+(allTotal/100));
      totalTextField.setText(iTotal);
    }                                           

    private void latteCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                              
       double cLatte=Double.parseDouble(costOfDrinksTextField.getText());
       double Latte=Double.parseDouble(latteTextField.getText());
       double iLatte=1.99;
       
       if(latteCheckBox.isSelected())
       {
           i[1]=(Latte*iLatte)+cLatte;
           String pDrink=String.format("%.2f",i[1]);
           costOfDrinksTextField.setText(pDrink);
           latteTextField.setText(pDrink);
       }
    }                                             

    private void costOfDrinksTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void icedLatteCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                  
      double cIcedLatte=Double.parseDouble(costOfDrinksTextField.getText());
      double icedLatte=Double.parseDouble(icedLatteTextField.getText());
      double iIcedLatte=2.84;
      
      if(icedLatteCheckBox.isSelected())
      {
          i[0]=(iIcedLatte*icedLatte)+cIcedLatte;
          String icedDrink=String.format("%.2f",i[0]);
          costOfDrinksTextField.setText(icedDrink);
          icedLatteTextField.setText(icedDrink);
      }
      
      
    
      
    }                                                 

    private void espressoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       double cEspresso=Double.parseDouble(costOfDrinksTextField.getText());
       double espresso=Double.parseDouble(espressoTextField.getText());
       double iEspresso=3.08;
       
       if(espressoCheckBox.isSelected()){
           i[2]=(iEspresso*espresso)+cEspresso;
           String espressoDrink=String.format("%.2f",i[2]);
           costOfDrinksTextField.setText(espressoDrink);
           
           
       }
    }                                                

    private void cappuccinoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                   
       double cCappuccino=Double.parseDouble(costOfDrinksTextField.getText());
       double Cappuccino=Double.parseDouble(cappuccinoTextField.getText());
       double iCappucino=1.79;
       
       if(cappuccinoCheckBox.isSelected())
       {
           i[3]=(Cappuccino*iCappucino)+cCappuccino;
           String pDrink=String.format("%.2f",i[3]);
           costOfDrinksTextField.setText(pDrink);
           latteTextField.setText(pDrink);
       }
    }                                                  

    private void coffeeCakeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void coffeeCakeCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {                                                
        double cCoffeeCake=Double.parseDouble(costOfCakesTextField.getText());
       double coffeeCake=Double.parseDouble(coffeeCakeTextField.getText());
       double iCoffeeCake=.79;
       
       if(coffeeCakeCheckBox.isSelected())
       {
           i[5]=(coffeeCake*iCoffeeCake)+cCoffeeCake;
           String pDrink=String.format("%.2f",i[5]);
           costOfCakesTextField.setText(pDrink);
           coffeeCakeTextField.setText(pDrink);
       }
    }                                               

    private void carrotCakeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                   
            double cCarrotCake=Double.parseDouble(costOfCakesTextField.getText());
       double carrotCake=Double.parseDouble(carrotCakeTextField.getText());
       double iCarrotCake=.89;
       
       if(carrotCakeCheckBox.isSelected())
       {
           i[6]=(carrotCake*iCarrotCake)+cCarrotCake;
           String pDrink=String.format("%.2f",i[6]);
           costOfCakesTextField.setText(pDrink);
           carrotCakeTextField.setText(pDrink);
       }
    }                                                  

    private void shortCakeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       double cShortCake=Double.parseDouble(costOfCakesTextField.getText());
       double shortCake=Double.parseDouble(shortCakeTextField.getText());
       double iShortCake=1.99;
       
       if(shortCakeCheckBox.isSelected())
       {
           i[7]=(shortCake*iShortCake)+cShortCake;
           String pDrink=String.format("%.2f",i[7]);
           costOfCakesTextField.setText(pDrink);
           shortCakeTextField.setText(pDrink);
       }
    }                                                 

    private void cheeseCakeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                   
       double cCheeseCake=Double.parseDouble(costOfCakesTextField.getText());
       double cheeseCake=Double.parseDouble(cheeseCakeTextField.getText());
       double iCheeseCake=1.99;
       
       if(cheeseCakeCheckBox.isSelected())
       {
           i[8]=(cheeseCake*iCheeseCake)+cCheeseCake;
           String pDrink=String.format("%.2f",i[8]);
           costOfCakesTextField.setText(pDrink);
           cheeseCakeTextField.setText(pDrink);
       }
    }                                                  

    private void peachCakeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       double cPeachCake=Double.parseDouble(costOfCakesTextField.getText());
       double peachCake=Double.parseDouble(peachCakeTextField.getText());
       double iPeachCake=3.00;
       
       if(peachCakeCheckBox.isSelected())
       {
           i[9]=(peachCake*iPeachCake)+cPeachCake;
           String pDrink=String.format("%.2f",i[9]);
           costOfCakesTextField.setText(pDrink);
           peachCakeTextField.setText(pDrink);
       }
    }                                                 

    private void totalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox cappuccinoCheckBox;
    private javax.swing.JTextField cappuccinoTextField;
    private javax.swing.JCheckBox carrotCakeCheckBox;
    private javax.swing.JTextField carrotCakeTextField;
    private javax.swing.JCheckBox cheeseCakeCheckBox;
    private javax.swing.JTextField cheeseCakeTextField;
    private javax.swing.JCheckBox coffeeCakeCheckBox;
    private javax.swing.JTextField coffeeCakeTextField;
    private javax.swing.JTextField costOfCakesTextField;
    private javax.swing.JTextField costOfDrinksTextField;
    private javax.swing.JCheckBox espressoCheckBox;
    private javax.swing.JTextField espressoTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JCheckBox icedCappuccinoCheckBox;
    private javax.swing.JTextField icedCappuccinoTextField;
    private javax.swing.JCheckBox icedLatteCheckBox;
    private javax.swing.JTextField icedLatteTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JCheckBox latteCheckBox;
    private javax.swing.JTextField latteTextField;
    private javax.swing.JCheckBox peachCakeCheckBox;
    private javax.swing.JTextField peachCakeTextField;
    private javax.swing.JButton receiptButton;
    private javax.swing.JTextArea receiptTextArea;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField serviceChargeTextField;
    private javax.swing.JCheckBox shortCakeCheckBox;
    private javax.swing.JTextField shortCakeTextField;
    private javax.swing.JTextField subTotalTextField;
    private javax.swing.JTextField taxTextField;
    private javax.swing.JButton totalButton;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration                   
}
