/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VirtualPianos;

import sun.audio.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Pentazoid
 */
public class VirtualPiano extends javax.swing.JFrame {

    /**
     * Creates new form VirtualPiano
     */
    public VirtualPiano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        CSharpeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        virtualSteelDrummerCheckBox = new javax.swing.JCheckBox();
        DButton = new javax.swing.JButton();
        MusicNotesCheckBox = new javax.swing.JCheckBox();
        DSharpeButton = new javax.swing.JButton();
        CButton = new javax.swing.JButton();
        EButton = new javax.swing.JButton();
        FButton = new javax.swing.JButton();
        GButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 8));
        jPanel1.setLayout(null);

        CSharpeButton.setBackground(new java.awt.Color(0, 0, 0));
        CSharpeButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CSharpeButton.setForeground(new java.awt.Color(255, 255, 255));
        CSharpeButton.setText("C#");
        CSharpeButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        CSharpeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSharpeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CSharpeButton);
        CSharpeButton.setBounds(70, 100, 69, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("VirtualPiano");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 0, 370, 70);

        virtualSteelDrummerCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        virtualSteelDrummerCheckBox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        virtualSteelDrummerCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        virtualSteelDrummerCheckBox.setText("Virtual Steel Drums");
        jPanel1.add(virtualSteelDrummerCheckBox);
        virtualSteelDrummerCheckBox.setBounds(420, 60, 220, 40);

        DButton.setBackground(java.awt.Color.white);
        DButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DButton.setText("D");
        DButton.setToolTipText("");
        DButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DButton);
        DButton.setBounds(110, 100, 73, 470);

        MusicNotesCheckBox.setBackground(new java.awt.Color(0, 0, 0));
        MusicNotesCheckBox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MusicNotesCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        MusicNotesCheckBox.setText("Music Notes");
        MusicNotesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicNotesCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(MusicNotesCheckBox);
        MusicNotesCheckBox.setBounds(40, 50, 200, 40);

        DSharpeButton.setBackground(new java.awt.Color(0, 0, 0));
        DSharpeButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DSharpeButton.setForeground(new java.awt.Color(255, 255, 255));
        DSharpeButton.setText("D#");
        DSharpeButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DSharpeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSharpeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DSharpeButton);
        DSharpeButton.setBounds(150, 90, 70, 230);

        CButton.setBackground(java.awt.Color.white);
        CButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CButton.setText("C");
        CButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        CButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CButton);
        CButton.setBounds(30, 100, 73, 470);

        EButton.setBackground(java.awt.Color.white);
        EButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EButton.setText("E");
        EButton.setToolTipText("");
        EButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        EButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EButton);
        EButton.setBounds(190, 100, 73, 470);

        FButton.setBackground(java.awt.Color.white);
        FButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        FButton.setText("F");
        FButton.setToolTipText("");
        FButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        FButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FButtonActionPerformed(evt);
            }
        });
        jPanel1.add(FButton);
        FButton.setBounds(270, 100, 73, 470);

        GButton.setBackground(java.awt.Color.white);
        GButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        GButton.setText("G");
        GButton.setToolTipText("");
        GButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GButton);
        GButton.setBounds(350, 100, 73, 470);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 780, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DButtonActionPerformed
        InputStream iAudio;
        if(MusicNotesCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\d.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        if(virtualSteelDrummerCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\d.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_DButtonActionPerformed

    private void CSharpeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSharpeButtonActionPerformed
         InputStream iAudio;
        if(MusicNotesCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\c#.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
          if(virtualSteelDrummerCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\steel.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_CSharpeButtonActionPerformed

    private void MusicNotesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicNotesCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicNotesCheckBoxActionPerformed

    private void CButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CButtonActionPerformed
       InputStream iAudio;
        if(MusicNotesCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\c.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        if(virtualSteelDrummerCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\steel.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_CButtonActionPerformed

    private void EButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonActionPerformed
        InputStream iAudio;
        if(MusicNotesCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\e.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        if(virtualSteelDrummerCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\d.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_EButtonActionPerformed

    private void DSharpeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSharpeButtonActionPerformed
      InputStream iAudio;
        if(MusicNotesCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\d#.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        if(virtualSteelDrummerCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\steel.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_DSharpeButtonActionPerformed

    private void FButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FButtonActionPerformed
         InputStream iAudio;
        if(MusicNotesCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\f.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        if(virtualSteelDrummerCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\f.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_FButtonActionPerformed

    private void GButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GButtonActionPerformed
            InputStream iAudio;
        if(MusicNotesCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\gg.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        if(virtualSteelDrummerCheckBox.isSelected()){
            try{
                iAudio=new FileInputStream(new File("C:\\Users\\Music Notes\\f.wav"));
                AudioStream iMusic=new AudioStream(iAudio);
                AudioPlayer.player.start(iMusic);
                
            }catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_GButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
             java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirtualPiano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VirtualPiano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CButton;
    private javax.swing.JButton CSharpeButton;
    private javax.swing.JButton DButton;
    private javax.swing.JButton DSharpeButton;
    private javax.swing.JButton EButton;
    private javax.swing.JButton FButton;
    private javax.swing.JButton GButton;
    private javax.swing.JCheckBox MusicNotesCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox virtualSteelDrummerCheckBox;
    // End of variables declaration//GEN-END:variables
}
